### ISSUE TITLE
the script is not working correctly

### ISSUE THREAD

**Issue by R4290N** [mattmarkwick/fooocus-gallery#8]
Hello! I would like to express my gratitude and respect for the work you have done.
I installed your script, it is a very necessary and right tool for working with Fooocus, but there are problems: apparently, Fooocus has changed the html structure of log file and now the script is not working properly - seed is not shown, styles are not shown, the gallery hangs when you try to click the copy button. Please fix it if possible. Thank you very much!!!

**Comment by Ambratolm** [comment]
same here, also the seed.

**Comment by 925-Studio** [comment]
No doulbt Fooocus is an excllent tool for SD generation. But the 'view' and 'manage' those generated images issue  always bothers me. I'm glad the OP created this tool, it's very useful also the UI is stunning. I think the OP must put a lot of work into this. But like @R4290N said, after the update of Fooocus, the `html` structure has been changed. Any chance to update this great tool? Thanks in advance.

**Comment by mattmarkwick** [comment]
Hi, thanks for the feedback and sorry for the silence, it has been a busy end to the year. I'll take a look at updating this in the coming days while I have some time off.

**Comment by 925-Studio** [comment]
> Hi, thanks for the feedback and sorry for the silence, it has been a busy end to the year. I'll take a look at updating this in the coming days while I have some time off.

Good to hear, hope it won't take too much time of yours.

**Comment by mattmarkwick** [comment]
Hi folks, apologies for the delay on coming back to this, probably naïve of me to think I would have time to work on personal projects during the busy christmas period! Anyway, 2 months later and I've finally found a moment and the fooocus gallery is now updated to support current version of Fooocus.

In theory the script should update automatically in Tampermonkey if you have that set, but otherwise just open the script in Tampermonkey and go to File->Check for updates to force it.
